namespace Core.Others
{
    public enum VehicleMake
    {
        Toyota,
        Honda,
        Ford,
        Chevrolet,
        Nissan,
        BMW,
        MercedesBenz,
        Audi,
        Volkswagen,
        Hyundai,
        Kia,
        Subaru,
        Mazda,
        Tesla,
        Jeep,
        Dodge,
        Lexus,
        GMC,
        Volvo,
        Porsche,
        Jaguar,
        LandRover,
        Mitsubishi,
        Fiat,
        AlfaRomeo
    }
}
